  - name: Create a directory
    file:
      path: /data
      state: directory
      mode: "u=rwx,g=rwx,o=rwx"

  - name: Install LogStash
    get_url:
      url: https://artifacts.elastic.co/downloads/logstash/logstash-6.8.15.tar.gz
      dest: /data/logstash-6.8.15.tar.gz
      mode: 0755

  - name: Extract logstash
    unarchive:
      src: /data/logstash-6.8.15.tar.gz
      dest: /data/
      remote_src: yes
      creates: /data/logstash-6.8.15/cof.d/inputs/conf

  - name: Insert LogStash unit file
    template:
      src: logstash.service.j2
      dest: /etc/systemd/system/logstash.service
      mode: 0644

  - name: Start/Stop LogStash
    template:
      src: start.sh.j2
      dest: /data/logstash-6.8.15/start.sh
      mode: 0754

  - name: Create directory
    file:
      path: /data/logstash-6.8.15/conf.d
      state: directory
      mode: 0777

  - name: Update config default
    template:
      src: inputs.conf.j2
      dest: /data/logstash-6.8.15/conf.d/inputs.conf
      mode: 0660

  - name: Daemon Reload
    systemd:
      daemon_reload: yes

  - name: Start LogStash
    service:
      name: logstash
      state: started
      enabled: yes

  - name: Create a directory
    file:
      path: /data
      state: directory
      mode: "u=rwx,g=rwx,o=rwx"

  - name: Install LogStash
    get_url:
      url: https://artifacts.elastic.co/downloads/logstash/logstash-6.8.15.tar.gz
      dest: /data/logstash-6.8.15.tar.gz
      mode: 0755

  - name: Extract logstash
    unarchive:
      src: /data/logstash-6.8.15.tar.gz
      dest: /data/
      remote_src: yes
      creates: /data/logstash-6.8.15/cof.d/inputs/conf

  - name: Insert LogStash unit file
    template:
      src: logstash.service.j2
      dest: /etc/systemd/system/logstash.service
      mode: 0644

  - name: Start/Stop LogStash
    template:
      src: start.sh.j2
      dest: /data/logstash-6.8.15/start.sh
      mode: 0754

  - name: Create directory
    file:
      path: /data/logstash-6.8.15/conf.d
      state: directory
      mode: 0777

  - name: Update config default
    template:
      src: inputs.conf.j2
      dest: /data/logstash-6.8.15/conf.d/inputs.conf
      mode: 0660

  - name: Daemon Reload
    systemd:
      daemon_reload: yes

  - name: Start LogStash
    service:
      name: logstash
      state: started
      enabled: yes

