  - name: Install ElasticSearch
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.15.tar.gz
      dest: /data/elasticsearch-6.8.15.tar.gz
      mode: 0755

  - name: Selinux Permissive Ubuntu remote server
    selinux:
      policy: targeted
      state: permissive
    when: ansible_os_family == "Ubuntu"

  - name: Update sysctl
    sysctl:
      name: vm.max_map_count
      value: "262144"
      sysctl_set: yes

  - name: Add a user
    user:
      name: elasticsearch
      comment: elasticsearch user

  - name: Create a directory
    file:
      path: /data
      state: directory
      mode: 0777

  - name: Extract ElasticSearch
    unarchive:
      src: /data/elasticsearch-6.8.15.tar.gz
      dest: /data/
      remote_src: yes
      creates: /data/elasticsearch-6.8.15/config/elasticsearch.yml

  - name: Insert ElasticSearch systemd
    template:
      src: elasticsearch.service.j2
      dest: /etc/systemd/system/elasticsearch.service
      mode: 0644

  - name: Insert ElasticSearch config
    template:
      src: elasticsearch.yml.j2
      dest: /data/elasticsearch-6.8.15/config/elasticsearch.yml
      mode: 0660

  - file:
      path: /data/elasticsearch-6.8.15
      owner: elasticsearch
      group: elasticsearch
      recurse: yes

  - name: Reload the Daemon
    systemd:
      daemon_reload: yes

  - name: Start ElasticSearch
    service:
      name: elasticsearch
      state: started
      enabled: yes

  - name: Selinux Permissive CentOS remote server
    selinux:
      policy: targeted
      state: permissive
    when: ansible_os_family == "RedHat"

  - name: Update sysctl
    sysctl:
      name: vm.max_map_count
      value: "262144"
      sysctl_set: yes

  - name: Add a user
    user:
      name: elasticsearch
      comment: elasticsearch user

  - name: Create a directory
    file:
      path: /data
      state: directory
      mode: 0777

  - name: Install ElasticSearch
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.15.tar.gz
      dest: /data/elasticsearch-6.8.15.tar.gz
      mode: 0755

  - name: Extract ElasticSearch
    unarchive:
      src: /data/elasticsearch-6.8.15.tar.gz
      dest: /data/
      remote_src: yes
      creates: /data/elasticsearch-6.8.15/config/elasticsearch.yml

  - name: Insert ElasticSearch systemd
    template:
      src: elasticsearch.service.j2
      dest: /etc/systemd/system/elasticsearch.service
      mode: 0644

  - name: Insert ElasticSearch config
    template:
      src: elasticsearch.yml.j2
      dest: /data/elasticsearch-6.8.15/config/elasticsearch.yml
      mode: 0660

  - file:
      path: /data/elasticsearch-6.8.15
      owner: elasticsearch
      group: elasticsearch
      recurse: yes

  - name: Reload the Daemon
    systemd:
      daemon_reload: yes

  - name: Start ElasticSearch
    service:
      name: elasticsearch
      state: started
      enabled: yes
